/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qyazivfpnboveqfcmrby"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5YXppdmZwbmJvdmVxZmNtcmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NTEyNjksImV4cCI6MjA5MDAyNzI2OX0.DTLj2bYFz7-pbScV9IhutQamBNOQiEX6fL-Jjnk4kZs"